import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'
import { useState } from 'react'
import { Card, } from '../components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const APP_ID = "9e25da68"
  const APP_KEY = "7d5e0026f8fec934ae95b193c7dfbeb2"

  const [recipes, setRecipes] = useState([]);

  const [search, setSearch] = useState("")

  const [query, setQuery] = useState('chicken')


  useEffect( () => {
    getRecipes()
  }, [query]);
  
  const getRecipes = async ()=>{
      const response = await fetch (`https://api.edamam.com/search?q=${query}&app_id=${APP_ID}&app_key=${APP_KEY}`)
      const data = await response.json();
      setRecipes(data.hits);
      console.log(data.hits);
  };

  const updateSearch = e => {
    setSearch(e.target.value);
  }

  const getSearch = e => {
    e.preventDefault();
    setQuery(search);
    setSearch("");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-black flex justify-center align-middle text-center '>
      <section>
      <form onSubmit={getSearch} className='search-form mt-5'>
      <input value={search} onChange={updateSearch} className='search-bar' type="text" />
      <button  className='search-button' type='submit'>
      search
      </button>
      </form>
       

        <div className='grid grid-cols-1 lg:grid-cols-4 gap-5'>
        {recipes.map(recipe => (
          <Card 
          key={recipe.recipe.label}
          title={recipe.recipe.label} calories={recipe.recipe.calories} 
          image={recipe.recipe.image} ingredients = {recipe.recipe.ingredients}
          />
  ))}
        </div>
       

      </section>
      </div>

        
    </>
  )
}
